// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewParkingAvailabilityServer.Models;

#nullable disable

namespace NewParkingAvailabilityServer.Migrations
{
    [DbContext(typeof(ParkingSpaceContext))]
    [Migration("20251123203928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("NewParkingAvailabilityServer.Models.ParkingSpaceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("floor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("maintenanceAlert")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("occupied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpaceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
