// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewParkingAvailabilityServer.Models;

#nullable disable

namespace NewParkingAvailabilityServer.Migrations.PSTotalResults
{
    [DbContext(typeof(PSTotalResultsContext))]
    [Migration("20251124221202_PSFinal")]
    partial class PSFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("NewParkingAvailabilityServer.Models.PSTotalResultsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("objectInSpot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("parkingSpaceObstructed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("vehicle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PSTotalResultsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
