@NewParkingAvailabilityServer_HostAddress = https://localhost:7288

GET {{NewParkingAvailabilityServer_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{NewParkingAvailabilityServer_HostAddress}}/api/parkingspaceitems
Content-Type: application/json

{
  "floor": 8,
  "occupied": true,
  "maintenanceAlert": false
}

###

GET {{NewParkingAvailabilityServer_HostAddress}}/api/parkingspaceitems

###

@id=1
GET {{NewParkingAvailabilityServer_HostAddress}}/api/parkingspaceitems/{{id}}

###

PUT {{NewParkingAvailabilityServer_HostAddress}}/api/parkingspaceitems/1
Content-Type: application/json

{
  "id": 1,
  "floor": 2,
  "occupied": false,
  "maintenanceAlert": true
}

###
@id=6
DELETE {{NewParkingAvailabilityServer_HostAddress}}/api/parkingspaceitems/{{id}}

###

POST {{NewParkingAvailabilityServer_HostAddress}}/api/parkingspaceitems
Content-Type: application/json

{
  "floor": 3,
  "occupied": true,
  "maintenanceAlert": true
}

###

POST {{NewParkingAvailabilityServer_HostAddress}}/api/pstotalresultsitems
Content-Type: application/json

{
  "vehicle": true,
  "objectInSpot": true,
  "parkingSpaceObstructed": true
}

###

GET {{NewParkingAvailabilityServer_HostAddress}}/api/pstotalresultsitems

###

PUT {{NewParkingAvailabilityServer_HostAddress}}/api/pstotalresultsitems/1
Content-Type: application/json

{
  "id": 1,
  "vehicle": true,
  "objectInSpot": true,
  "parkingSpaceObstructed": true
}

###
