// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewParkingAvailabilityServer.Models;

#nullable disable

namespace NewParkingAvailabilityServer.Migrations.ObjectInSpot
{
    [DbContext(typeof(ObjectInSpotContext))]
    [Migration("20251126171520_ObjectInSpots")]
    partial class ObjectInSpots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("NewParkingAvailabilityServer.Models.ObjectInSpotItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("objectInSpot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ObjectInSpotItems");
                });
#pragma warning restore 612, 618
        }
    }
}
