// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewParkingAvailabilityServer.Models;

#nullable disable

namespace NewParkingAvailabilityServer.Migrations.ObjectInSpot
{
    [DbContext(typeof(ObjectInSpotContext))]
    [Migration("20260303195912_ErrorForObjectInSpot")]
    partial class ErrorForObjectInSpot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("NewParkingAvailabilityServer.Models.ObjectInSpotItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("error")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("objectInSpot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ObjectInSpotItems");
                });
#pragma warning restore 612, 618
        }
    }
}
