// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewParkingAvailabilityServer.Models;

#nullable disable

namespace NewParkingAvailabilityServer.Migrations.OpenCVResults
{
    [DbContext(typeof(OpenCVResultsContext))]
    partial class OpenCVResultsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("NewParkingAvailabilityServer.Models.OpenCVResultsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("parkingSpaceObstructed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("vehicle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OpenCVResultsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
