// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewParkingAvailabilityServer.Models;

#nullable disable

namespace NewParkingAvailabilityServer.Migrations.OpenCVPolygons
{
    [DbContext(typeof(OpenCVPolygonsContext))]
    partial class OpenCVPolygonsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("NewParkingAvailabilityServer.Models.OpenCVPolygonsItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("polygonPoints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpenCVPolygonsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
